"""add enum for submission state

Revision ID: 151563cf838c
Revises: 1ba854e76d84
Create Date: 2024-05-31 19:21:53.182728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151563cf838c'
down_revision: Union[str, None] = '1ba854e76d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('state', sa.Enum('Not Entered', 'Entered', 'Submitted', 'Pending Feedback', 'Complete', name='submissionstate'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'state')
    # ### end Alembic commands ###
