"""more contest datetime fields

Revision ID: 1ba854e76d84
Revises: 77b8587785b6
Create Date: 2024-05-30 20:20:58.974742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba854e76d84'
down_revision: Union[str, None] = '77b8587785b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('submission_start_date', sa.DateTime(), nullable=True))
    op.add_column('contests', sa.Column('submission_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'submission_end_date')
    op.drop_column('contests', 'submission_start_date')
    # ### end Alembic commands ###
