"""initial revision

Revision ID: 4e89bba7c6e7
Revises: 
Create Date: 2024-06-06 21:09:42.242032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from extras.supabase_user_creation import supabase_user_creation_upgrade, supabase_user_creation_downgrade

# revision identifiers, used by Alembic.
revision: str = '4e89bba7c6e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('submission_start_date', sa.DateTime(), nullable=True),
    sa.Column('submission_end_date', sa.DateTime(), nullable=True),
    sa.Column('voting_start_date', sa.DateTime(), nullable=True),
    sa.Column('voting_end_date', sa.DateTime(), nullable=True),
    sa.Column('stem_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_id'), 'contests', ['id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('submission_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('Enter Contest', 'Download Stems', 'Submit Mix', 'Give Feedback', 'Check Results', name='submissionstate'), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_table('contest_results',
    sa.Column('contest_results_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('num_feedbacks', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('contest_results_id')
    )
    op.create_index(op.f('ix_contest_results_contest_results_id'), 'contest_results', ['contest_results_id'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('submission_1_id', sa.Integer(), nullable=False),
    sa.Column('submission_2_id', sa.Integer(), nullable=False),
    sa.Column('winner_submission_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text_1', sa.Text(), nullable=True),
    sa.Column('feedback_text_2', sa.Text(), nullable=True),
    sa.Column('rater_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['rater_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_1_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['submission_2_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['winner_submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedback_feedback_id'), 'feedback', ['feedback_id'], unique=False)
    # ### end Alembic commands ###

    # set row level security and create trigger to update users table from supabase's auth.users
    supabase_user_creation_upgrade()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_contest_results_contest_results_id'), table_name='contest_results')
    op.drop_table('contest_results')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_contests_id'), table_name='contests')
    op.drop_table('contests')
    op.drop_table('users')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###

    supabase_user_creation_downgrade()
