"""change submission_url field name

Revision ID: 6eb2a0816a54
Revises: 4e89bba7c6e7
Create Date: 2024-06-07 20:45:06.384490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb2a0816a54'
down_revision: Union[str, None] = '4e89bba7c6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('submission_file_path', sa.String(), nullable=True))
    op.drop_column('submissions', 'submission_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('submission_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('submissions', 'submission_file_path')
    # ### end Alembic commands ###
