"""simplify stems

Revision ID: 77b8587785b6
Revises: 11d0f0cadcf9
Create Date: 2024-05-28 20:44:10.597565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77b8587785b6'
down_revision: Union[str, None] = '11d0f0cadcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stems_id', table_name='stems')
    op.drop_table('stems')
    op.add_column('contests', sa.Column('stem_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'stem_url')
    op.create_table('stems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stem_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stem_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], name='stems_contest_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stems_pkey')
    )
    op.create_index('ix_stems_id', 'stems', ['id'], unique=False)
    # ### end Alembic commands ###
